on:
  push:
    tags:
      - 'v*'
    paths:
      - repos/fdbt-emailer/**
  workflow_dispatch:

name: "fdbt-emailer-prod"

defaults:
  run:
    working-directory: ./repos/fdbt-emailer

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: prod
    environment:
      name: prod

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build-all-functions-${{ env.WORKSPACE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # 6.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update multi-operator-action-required-emailer lambda
        uses: "./.github/workflows/templates/update_lambda"
        with:
          repo: fdbt-emailer
          lambda: fdbt-multi-operator-action-required-emailer
          environment: ${{ env.WORKSPACE }}

      - name: Update multi-operator-product-complete-emailer lambda
        uses: "./.github/workflows/templates/update_lambda"
        with:
          repo: fdbt-emailer
          lambda: fdbt-multi-operator-product-complete-emailer
          environment: ${{ env.WORKSPACE }}
